### ISSUE TITLE
File downloaded is empty

### ISSUE THREAD

**Issue by digitalgutenberg** [UtkarshGpta/bing-desktop-wallpaper-changer#2]
Hi there! 

Interesting script! I have a peculiar problem, I've installed python-lxml and python-bs4, but when I run the script, the file that is created in the BingWallpapers directory is empty.

Currently there is a file there called "20160805.jpg", but it is 0 bytes. When I delete the file and run the script again, the same thing happens. (I've tried this several times.)

Any ideas?

I run Gnome 3.20/Debian Stretch (testing), my resolution is 1920*1080 and I have two monitors. I'll be happy to provide more information upon request!

Cheers!

**Comment by shoeyn** [comment]
Same issue here, would love to try this script, Ubuntu 16.04, same dual monitors at 1920x1080.
The issue does seem to be with getting the screen size, just manually setting the size 1920, 1080 makes the script work

I've created a pull request which hopefully resolves the issue #3

**Comment by utkarshgpta** [comment]
@lmr : Have a look at #5. For each image, Bing does not provide every resolution. We could either resize it or use just a single image.

**Comment by digitalgutenberg** [comment]
The commit by shoeyn did solve the problem on my end! Thanks guys!
