### ISSUE TITLE
wallpaper doesn't change daily

### ISSUE THREAD

**Issue by yasharne** [UtkarshGpta/bing-desktop-wallpaper-changer#21]
App works fine whenever os boots but it doesn't change wallpaper daily or hourly

**Comment by truongan** [comment]
Manually run main.py at the start of the day can be a work around.

**Comment by Sim4n6** [comment]
I am working on fixing that. Please check issue #12

**Comment by utkarshgpta** [comment]
I guess Bing releases wallpaper every 24 hrs. So we don't need to change that.
We can add an option for user for setting the interval for which the user wants to check for a new wallpaper. That may solve it to an extent.

**Comment by truongan** [comment]
@UtkarshGpta: I agree we don't need to change that. The application should be keep simple, it's only do the work once every 24 hours and thus should not be running as a daemon.

But for those who keep your machine running longer than 1 day, setting a timer to automatically start the application is the way to go, not changing the application. 

I have been successfully set up a systemd.timer to run this application once the machine start and every day afterward. I will include detail instruction in READ.ME and make a pull request soon. That would close this issue I suppose.

**Comment by Wtower** [comment]
Unless I'm somewhere mistaken, this does not seem to work with any of my Ubuntu 16.04's.

**Comment by truongan** [comment]
@Wtower: I have successfully use systemd.timer on my archlinux. Didn't have ubuntu to test on. You should start a new issue regards systemd.timer, you and I can tracking the problem down.
