### ISSUE TITLE
Make download path configurable

### ISSUE THREAD

**Issue by tigre-bleu** [UtkarshGpta/bing-desktop-wallpaper-changer#25]
The script is working nicely, but it would be handy to have the download path as a configurable item.

For instance via command line argument or via a configuration item in the .ini file (or both).

**Comment by Theodin** [comment]
I second that.
Or make it use the default localised picture folder instead of a hard coded ~/Pictures/BingWallpapers.
Thanks for the script nontheless!

**Comment by adamwojs** [comment]
This issue can be closed now ;-)

**Comment by Vistaus** [comment]
It can't be closed yet as the referenced commit breaks the whole thing. So there's still no configurability.

```
vistaus@vistaus-arch:~/Apps/bing-desktop-wallpaper-changer$ python main.py 
Traceback (most recent call last):
  File "main.py", line 378, in <module>
    main()
  File "main.py", line 370, in main
    with open(download_path + "/image-details.txt", "a+") as myfile:
UnboundLocalError: local variable 'download_path' referenced before assignment
vistaus@vistaus-arch:~/Apps/bing-desktop-wallpaper-changer$
```

**Comment by utkarshgpta** [comment]
@adamwojs : Look into the issue, there's a problem showing up as reported by @Vistaus.

**Comment by adamwojs** [comment]
Problem should be resolved, but i've mentioned in PR description: probably there was some other exception before initialization download_path variable.

**Comment by utkarshgpta** [comment]
@adamwojs It has been resolved! :)

**Comment by Vistaus** [comment]
I can confirm it's fixed now, thanks! :smile:

**Comment by simonbcn** [comment]
It lacks documentation about this setting.
In any case, I think this download path should be localised.
