### ISSUE TITLE
Issues when I run pyton main.py manually.

### ISSUE THREAD

**Issue by gohv** [UtkarshGpta/bing-desktop-wallpaper-changer#33]
Hey,
My wallpaper didnt change this morning and when I run main.py manually I received the below :

Traceback (most recent call last):
  File "main.py", line 378, in <module>
    main()
  File "main.py", line 370, in main
    with open(download_path + "/image-details.txt", "a+") as myfile:
UnboundLocalError: local variable 'download_path' referenced before assignment

If I run it as root I receive a popup saying wallpaper unchaged, because it exists in wallpapers directory, but atm my BIng Wallpaper directory is empty.

The startup script does not work as well.
Is there something I can do to ammend this?

**Comment by Vistaus** [comment]
I had the same problem. The latest commit has fixed it.
