### ISSUE TITLE
Latest commits break bing-desktop-wallpaper-changer

### ISSUE THREAD

**Issue by Vistaus** [UtkarshGpta/bing-desktop-wallpaper-changer#39]
See the attached screenshot for the exact error message (notification is at the upper right).

Please fix this :)
![screenshot from 2016-10-28 10-55-14](https://cloud.githubusercontent.com/assets/1716229/19800885/28d23642-9cfd-11e6-83ee-308ab2c9d7d1.png)

**Comment by utkarshgpta** [comment]
It's been working fine on mine.

**Comment by utkarshgpta** [comment]
@Alzemand Have a look at this!

**Comment by Alzemand** [comment]
It has worked well in my too. The last commit does not possess concatenation, this is the main () function. Try running with Python 3. See my debug

![debug](https://cloud.githubusercontent.com/assets/10548468/19807983/5a3f9356-9d01-11e6-8ae3-ec17c81cbffc.png)

![giterro](https://cloud.githubusercontent.com/assets/10548468/19807982/5a3d4c68-9d01-11e6-9e45-446481b1f73a.png)

**Comment by Vistaus** [comment]
I'm already (always) running it with Python 3...

Also rebooted to no avail; the error message's still there. You can say it's not due to the latest commits but then why did it work fine w/o any error messages before the latest commits? (i.e. yesterday)

**Comment by Alzemand** [comment]
Sorry, Please run with python 2. You are right, the problem when running with python 3

@jhsoby there is a commit her the day before. Can you help us?

**Comment by Vistaus** [comment]
It works with python 2. But up until yesterday (before I git pull'ed the latest commits) it worked fine with python 3. So something did break it...

**Comment by jhsoby** [comment]
It does indeed seem to stem from my commit; the function check_output from subprocess gives output in a different type in Python3 than it does in Python2. After some googling I found a solution that works in both Python2 and Python3, so I made a commit for that as you can see above. Sorry about the trouble, it didn't cross my mind that the function would not be compatible with Python3. I will remember to test for that from now on.

Note that the error message when the wallpaper is unchanged gives ugly output with Python3, but it does that even without my initial commit, so it's a different (though related) issue I think.

**Comment by Vistaus** [comment]
Thank you so much for solving it! :smile: :smile_cat:

**Comment by Alzemand** [comment]
All right!
