### ISSUE TITLE
Script Stopped Running

### ISSUE THREAD

**Issue by Yashwanthv21** [UtkarshGpta/bing-desktop-wallpaper-changer#47]
I installed anaconda in my system and later removed it, this script doesn't run after that.
 I tried importing **gi** manually it worked.
but  `gi.require_version('Gtk', '3.0')` gives error as below
`Traceback (most recent call last):
  File "main.py", line 28, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: 'module' object has no attribute 'require_version'`. 
**I tried a lot online but i dint find any fix, all other modules in python works file except this**
is there a problem in my packages or do we need to change the code?

**Comment by utkarshgpta** [comment]
Closed issue due to inactivity.
