### ISSUE TITLE
Fails to change wallpaper on Linux mint 18 KDE

### ISSUE THREAD

**Issue by vmumo** [UtkarshGpta/bing-desktop-wallpaper-changer#48]
Script runs successfully but a notification pops u saying wallpaper unchanged

**Comment by vmumo** [comment]
![screenshot_20161208_224713](https://cloud.githubusercontent.com/assets/9326061/21025149/7982543a-bd98-11e6-8ffd-b1bf23592f0d.png)

**Comment by utkarshgpta** [comment]
What's happening basically here is that whenever the script is run, it downloads the most recent wallpaper available sets it as wallpaper. Now if the script is run again, it checks whether the most recent wallpaper is downloaded or not - if yes, then it gives the message "Bing Wallpaper unchanged", if not then it downloads it and sets it as the wallpaper.
What you did is you ran the script, it downloaded the wallpaper, changed the wallpaper and then ran the script again - it checked the downloaded wallpapers and then gave the message "Bing Wallpaper unchanged" as the wallpaper is already present in the directory where it's downloaded.
It's a minor issue, would be glad if there could be a fix.
