### ISSUE TITLE
Doesn't work on Xubuntu 16.10

### ISSUE THREAD

**Issue by grumble9684** [UtkarshGpta/bing-desktop-wallpaper-changer#54]
Script seems to be configured successfully, notification "bing wallpaper changed" appears, as well as the downloaded wallpaper in the directory, however the wallpaper isn't actually changed

**Comment by PyGeek03** [comment]
As far as I'm concerned, this script only works on the Gnome desktop environment or closely related ones (such as Budgie), not XFCE.

**Comment by pevans91** [comment]
Please can there be support for XFCE added in? I share the same problem as the OP.

Thanks :)

**Comment by utkarshgpta** [comment]
Closed issue due to inactivity.
