### ISSUE TITLE
Default path problem

### ISSUE THREAD

**Issue by ghost** [UtkarshGpta/bing-desktop-wallpaper-changer#64]
Good afternoon,

Well, with default installation, I always get error:
[Errno 2] No such file or directory: '/"/home/eko/Pictures/BingWallpapers/"/20171001.jpg'

But, after I change get_download_path(), it has no such problem again. Here is the get_download_path():
def get_download_path():
         default_path = "/home/eko/Pictures/BingWallpapers/"
         return default_path

**Comment by utkarshgpta** [comment]
Closed issue due to inactivity.
