### ISSUE TITLE
not work in mac

### ISSUE THREAD

**Issue by yingxincui** [UtkarshGpta/bing-desktop-wallpaper-changer#67]
GitHub: <https://github.com/UtkarshGpta/bing-desktop-wallpaper-changer>
Contributors: <https://github.com/UtkarshGpta/bing-desktop-wallpaper-changer/network/members>

uname: illegal option -- o
usage: uname [-amnprsv]
cat: /etc/issue: No such file or directory
cat: /etc/issue: No such file or directory
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
./installer.sh: line 215: [: !=: unary operator expected
./installer.sh: line 217: [: !=: unary operator expected
./installer.sh: line 219: [: !=: unary operator expected

Installer: Error 3 (Unknown package manager. Please report to GitHub!)!

**Comment by ghost** [comment]
BDWC (Installer and Python module) currently works in Linux with GNOME-based DE.

Thus, I have no plans to make "Installer for macOS". (Also we need to find a way to change wallpapers on macOS.)

Sorry :-)
