### ISSUE TITLE
Fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by yingw** [UtkarshGpta/bing-desktop-wallpaper-changer#68]
Works fine before, but fail when these day I upgrade to Ubuntu 18.04
It echos:
```
rm: cannot remove '/opt/bing-desktop-wallpaper-changer/.gitignore': No such file or directory

Executing bing-desktop-wallpaper-changer...
Traceback (most recent call last):
  File "/usr/bin/bingwallpaper", line 429, in <module>
    main()
  File "/usr/bin/bingwallpaper", line 424, in main
    app_notification.show()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```

I installed python 2.7 and gi module

```
sudo apt-get install python2.7 python2.7-dev
sudo ln -s /usr/bin/python2.7 /usr/bin/python
sudo apt install python-gi
```

**Comment by ghost** [comment]
@UtkarshGpta 
Maybe it's caused by a GTK module. Not sure why..

**Comment by UtkarshGpta** [comment]
Check these links out.

[https://stackoverflow.com/questions/35889348/libnotify-error-glib-error-the-name-org-freedesktop-notifications-was-not-provi](StackOverflow)
[https://bbs.archlinux.org/viewtopic.php?id=75078](ArchLinux)

**Comment by utkarshgpta** [comment]
Check these links out.

[ArchLinux](https://bbs.archlinux.org/viewtopic.php?id=75078)

[StackOverflow](https://stackoverflow.com/questions/35889348/libnotify-error-glib-error-the-name-org-freedesktop-notifications-was-not-provi)

**Comment by ghost** [comment]
@UtkarshGpta Please add **bug** and **help wanted**  tag :)

> Please contribute to this bug if you're an Ubuntu 18.04 user.

**Comment by ghost** [comment]
Anyway, you can still use @neffo 's GNOME extension. 😉

**Comment by utkarshgpta** [comment]
Closed issue due to inactivity.
