### ISSUE TITLE
[Errno 13] Permission denied: u'/home/user/Pictures/BingWallpapers/20180223.jpg

### ISSUE THREAD

**Issue by AntonioSerrano** [UtkarshGpta/bing-desktop-wallpaper-changer#69]
I have some permission issues when launching Bing Desktop Wallpaper Changer in Ubuntu. It appears a notification stating "[Errno 13] Permission denied: u'/home/user/Pictures/BingWallpapers/20180223.jpg". I tried to give permission to bingwallpaper executable in /usr/bin via `sudo chmod 777 bingwallpaper` but the problems persists. Any clue? Thx

**Comment by RoberWare** [comment]
Check this out https://github.com/UtkarshGpta/bing-desktop-wallpaper-changer/issues/72
