### ISSUE TITLE
Description is not updated at midnight

### ISSUE THREAD

**Issue by alexisLefebvre** [UtkarshGpta/bing-desktop-wallpaper-changer#70]
After midnight, wallpaper is updated but the description in the menu bar is not updated and show description of yesterday's wallpaper.

**Comment by ghost** [comment]
Think that's the Bing servers issue. Whenever someone update his/her wallpaper, main.py (python module) requests to Bing's server and tries to get the wallpaper image and the description provided by Bing.

**Comment by ghost** [comment]
Anyway, please look at the main.py to see if there are any problems. I may be incorrect.

**Comment by alexisLefebvre** [comment]
I'm sorry, I reported this issue on the wrong repository. I use another GNOME Shell extension.
