### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by RoberWare** [UtkarshGpta/bing-desktop-wallpaper-changer#72]
My System: Linux Mint 19.1 Cinnamon 64 bits

I have just found a bug and I have fixed it for me.
When I installed the program it didn't work, but when I ran the main.py from the terminal, it worked.
Investigating even more, if I executed: "python main.py" it worked correctly but if I did it with "sudo python main.py" not
I discovered that it was a problem with the permits.

My solution:

- Keep the "bing-desktop-wallpaper-changer-master" folder inside the /home/$USER folder.

- Replace the /usr/bin/binwallpaper code with:
> #!/bin/bash
> python /home/roberto/bing-desktop-wallpaper-changer-master/bin/main.py

**Comment by RoberWare** [comment]
I hope it helps someone.

**Comment by utkarshgpta** [comment]
Thank you @RoberWare !
