### ISSUE TITLE
How do I run the script on a daily basis?

### ISSUE THREAD

**Issue by ghost** [UtkarshGpta/bing-desktop-wallpaper-changer#73]
I manually execute BDWC first using `sudo /opt/bing-desktop-wallpaper-changer/main.py` and then `/opt/bing-desktop-wallpaper-changer/main.py` after which the desktop wallpaper changes. But it's not scheduled to run daily. I've tried crontab with `DISPLAY:0` added and see that `main.py` is being executed but neither notification nor any wallpaper change occurs. How do I set it to run daily, say, at 2pm?

**Comment by utkarshgpta** [comment]
It runs every time you log onto your system. It checks for any new wallpaper from Microsoft using the JSON/XML returned. If there's an update it downloads and changes the wallpaper. As of now there's no scheduled time that we can mention, it simply runs everytime you log onto your system.
