### ISSUE TITLE
Does not work in Parrot OS.

### ISSUE THREAD

**Issue by kbarbora** [UtkarshGpta/bing-desktop-wallpaper-changer#75]
I was able to install it successfully, the images get downloaded, the problem is that the desktop does not change.

**Comment by utkarshgpta** [comment]
Hello @kbarbora, the command that is executed for changing the wallpaper to the newly downloaded one works on GNOMEdesktop environment. I'm not sure about Parrot OS whether it uses the same or not. Maybe you can fork this repository, replace the command with the one that would would work on your desktop environment for others to use as well. Cheers!
